# Generated by Django 2.2 on 2019-06-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190623_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
