# Generated by Django 2.2 on 2019-06-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190624_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='icon',
            new_name='fafa',
        ),
    ]
